{% set version = "43.0" %}

package:
  name: gsettings-desktop-schemas
  version: {{ version }}

source:
  url: https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas/-/archive/{{ version }}/gsettings-desktop-schemas-{{ version }}.tar.bz2
  sha256: 321ac4209394acd8293e980b5a0b921285621bbbbee1fcfff9402bff19d66c13
  patches:
    - pkgconfig_install_libdir.patch

build:
  skip: true  # [not linux]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - meson
    - make
    - pkg-config
    - cmake
    - gobject-introspection
    # glib is really a build tool?
    # though I don't know if it supports "cross compilation" in the way we expect it to.
    - glib
  host:
    - gobject-introspection
    # - libgirepository
    # - g-ir-host-tools

test:
  commands:
    - test -f ${PREFIX}/lib/pkgconfig/gsettings-desktop-schemas.pc
    - test -f ${PREFIX}/share/glib-2.0/schemas/org.gnome.desktop.default-applications.gschema.xml

about:
  home: https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas
  summary: 'A native style to bend Qt5/Qt6 applications to look like they belong into GNOME Shell.'
  summary: 'A collection of GSettings schemas for settings shared by various components of a desktop.'
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING

extra:
  recipe-maintainers:
    - hmaarrfk
